# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    tags:
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Checkout fess-parent
      uses: actions/checkout@v2
      with:
        repository: codelibs/fess-parent
        path: fess-parent
    - name: Install fess-parent
      run: |
        cd fess-parent
        mvn install
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: fess-ds-gsuite-14.6.1-FoldersPath
        tag_name: 14.6.1-FoldersPath
        body: This fork provides folders path information to crawled files.
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/fess-ds-gsuite-14.6.1-FoldersPath.jar
        asset_name: fess-ds-gsuite-14.6.1-FoldersPath.jar
        asset_content_type: application/java-archive
